field: 381ffcc0-0d5f-47a0-8186-4ba74d14a2d5 # Guestbox
fieldLayouts:
  b2b2ee63-4c70-490f-8b80-1826f93beeb8:
    tabs:
      -
        elements:
          -
            fieldUid: cf30349c-229e-4772-bb79-3833376b60cb # Message
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a91e7aa6-c9f1-4753-8b95-a448bfe66927 # Image Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cc7ca747-8398-4378-8b28-609d2a9f4fbe # destination Entry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  a91e7aa6-c9f1-4753-8b95-a448bfe66927: # Image Button
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: 'Image Button'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:4a914dde-98f1-4a3f-a2da-71d52cd6710f' # Uploads
      defaultUploadLocationSubpath: singleImage
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:4a914dde-98f1-4a3f-a2da-71d52cd6710f' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:4a914dde-98f1-4a3f-a2da-71d52cd6710f' # Uploads
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  cc7ca747-8398-4378-8b28-609d2a9f4fbe: # destination Entry
    contentColumnType: string
    fieldGroup: null
    handle: destination
    instructions: ''
    name: 'destination Entry'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  cf30349c-229e-4772-bb79-3833376b60cb: # Message
    contentColumnType: text
    fieldGroup: null
    handle: msg
    instructions: ''
    name: Message
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: guestbox
name: guestbox
sortOrder: 1
