field: fb3f817a-c099-44a0-bb06-02fbf4e2f533 # Social Media
fieldLayouts:
  161774df-7f79-4d8a-bb45-f4f1a008fb5f:
    tabs:
      -
        elements:
          -
            fieldUid: 6ea8daa1-0cd8-4961-940d-5523c3317724 # Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6e5b1f4b-ef68-41f9-99eb-c71c93d7a30e # destination
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6e5b1f4b-ef68-41f9-99eb-c71c93d7a30e: # destination
    contentColumnType: string(255)
    fieldGroup: null
    handle: destination
    instructions: ''
    name: destination
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
        - tel
        - email
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  6ea8daa1-0cd8-4961-940d-5523c3317724: # Name
    contentColumnType: text
    fieldGroup: null
    handle: socialName
    instructions: ''
    name: Name
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: social
name: social
sortOrder: 1
