contentColumnType: string
fieldGroup: 5ae88ae4-5daa-47ca-bc82-be62a483fc2e # Footer
handle: buttons
instructions: ''
name: 'Buttons Matrix'
searchable: false
settings:
  contentTable: '{{%matrixcontent_buttons}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
