contentColumnType: integer(10)
fieldGroup: 5ae88ae4-5daa-47ca-bc82-be62a483fc2e # Footer
handle: copyright
instructions: ''
name: 'Copyright Year'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: '0'
  prefix: null
  previewCurrency: ''
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
